
    -- countryt
    INSERT INTO country VALUES ('Afghanistan');
    INSERT INTO country VALUES ('Albania');
    INSERT INTO country VALUES ('Algeria');
    INSERT INTO country VALUES ('Angola');
    INSERT INTO country VALUES ('Andorra');
    INSERT INTO country VALUES ('Argentina');
    INSERT INTO country VALUES ('Armenia');
    INSERT INTO country VALUES ('Austria');
    INSERT INTO country VALUES ('Australia');
    INSERT INTO country VALUES ('Azerbaijan');
    INSERT INTO country VALUES ('Bangladesh');
    INSERT INTO country VALUES ('Belgium');
    INSERT INTO country VALUES ('Benin');
    INSERT INTO country VALUES ('Bhutan');
    INSERT INTO country VALUES ('Belize');
    INSERT INTO country VALUES ('Bolivia');
    INSERT INTO country VALUES ('Bosnia and Herzegovina');
    INSERT INTO country VALUES ('Botswana');
    INSERT INTO country VALUES ('Brunei');
    INSERT INTO country VALUES ('Bulgaria');
    INSERT INTO country VALUES ('Brazil');
    INSERT INTO country VALUES ('Burkina Faso');
    INSERT INTO country VALUES ('Canada');
    INSERT INTO country VALUES ('Cambodia');
    INSERT INTO country VALUES ('Cameroon');
    INSERT INTO country VALUES ('Central African Republic');
    INSERT INTO country VALUES ('Chad');
    INSERT INTO country VALUES ('Chile');
    INSERT INTO country VALUES ('China');
    INSERT INTO country VALUES ('Columbia');
    INSERT INTO country VALUES ('Congo');
    INSERT INTO country VALUES ('Czech Republic');
    INSERT INTO country VALUES ('Democratic Peoples Republic of Congo');
    INSERT INTO country VALUES ('Denmark');
    INSERT INTO country VALUES ('Dominican Republic');
    INSERT INTO country VALUES ('Ecuador');
    INSERT INTO country VALUES ('Egypt');
    INSERT INTO country VALUES ('El Salvador');
    INSERT INTO country VALUES ('Eritrea');
    INSERT INTO country VALUES ('Estonia');
    INSERT INTO country VALUES ('Ethiopia');
    INSERT INTO country VALUES ('Finland');
    INSERT INTO country VALUES ('Germany');
    INSERT INTO country VALUES ('Georgia');
    INSERT INTO country VALUES ('Ghana');
    INSERT INTO country VALUES ('Greece');
    INSERT INTO country VALUES ('Haiti');
    INSERT INTO country VALUES ('Hungary');
    INSERT INTO country VALUES ('Iran');
    INSERT INTO country VALUES ('Iraq');
    INSERT INTO country VALUES ('Ireland');
    INSERT INTO country VALUES ('Iceland');
    INSERT INTO country VALUES ('Italy');
    INSERT INTO country VALUES ('Indonesia');
    INSERT INTO country VALUES ('India');
    INSERT INTO country VALUES ('Ivory Coast');
    INSERT INTO country VALUES ('Japan');
    INSERT INTO country VALUES ('Jamaica');
    INSERT INTO country VALUES ('Kazakhstan');
    INSERT INTO country VALUES ('Kenya');
    INSERT INTO country VALUES ('Kuuba');
    INSERT INTO country VALUES ('Kuwait');
    INSERT INTO country VALUES ('Kyrgyzstan');
    INSERT INTO country VALUES ('Laos');
    INSERT INTO country VALUES ('Latvia');
    INSERT INTO country VALUES ('Lesotho');
    INSERT INTO country VALUES ('Libanon');
    INSERT INTO country VALUES ('Liberia');
    INSERT INTO country VALUES ('Libya');
    INSERT INTO country VALUES ('Lithuania');
    INSERT INTO country VALUES ('Luxembourg');
    INSERT INTO country VALUES ('Madagascar');
    INSERT INTO country VALUES ('Malaysia');
    INSERT INTO country VALUES ('Morocco');
    INSERT INTO country VALUES ('Mauritania');
    INSERT INTO country VALUES ('Mexico');
    INSERT INTO country VALUES ('Mongolia');
    INSERT INTO country VALUES ('Myanmar');
    INSERT INTO country VALUES ('Netherlands');
    INSERT INTO country VALUES ('Namibia');
    INSERT INTO country VALUES ('Nepal');
    INSERT INTO country VALUES ('Nigaraqua');
    INSERT INTO country VALUES ('Niger');
    INSERT INTO country VALUES ('Nigeria');
    INSERT INTO country VALUES ('North Korea');
    INSERT INTO country VALUES ('Norway');
    INSERT INTO country VALUES ('Oman');
    INSERT INTO country VALUES ('Pakistan');
    INSERT INTO country VALUES ('Panama');
    INSERT INTO country VALUES ('Papua New Guinea');
    INSERT INTO country VALUES ('Paraguay');
    INSERT INTO country VALUES ('Peru');
    INSERT INTO country VALUES ('Philippines');
    INSERT INTO country VALUES ('Poland');
    INSERT INTO country VALUES ('Portugal');
    INSERT INTO country VALUES ('France');
    INSERT INTO country VALUES ('Romania');
    INSERT INTO country VALUES ('Ruanda');
    INSERT INTO country VALUES ('Sweden');
    INSERT INTO country VALUES ('Saudi Arabia');
    INSERT INTO country VALUES ('Sambia');
    INSERT INTO country VALUES ('San Marino');
    INSERT INTO country VALUES ('Senegal');
    INSERT INTO country VALUES ('Serbia');
    INSERT INTO country VALUES ('Singapore');
    INSERT INTO country VALUES ('Slovakia');
    INSERT INTO country VALUES ('Slovenia');
    INSERT INTO country VALUES ('Somalia');
    INSERT INTO country VALUES ('South Africa');
    INSERT INTO country VALUES ('South Korea');
    INSERT INTO country VALUES ('South Sudan');
    INSERT INTO country VALUES ('Spain');
    INSERT INTO country VALUES ('Suriname');
    INSERT INTO country VALUES ('Switzerland');
    INSERT INTO country VALUES ('Syria');
    INSERT INTO country VALUES ('Tajikistan');
    INSERT INTO country VALUES ('Taiwan');
    INSERT INTO country VALUES ('Tanzania');
    INSERT INTO country VALUES ('Thailand');
    INSERT INTO country VALUES ('Togo');
    INSERT INTO country VALUES ('Turkey');
    INSERT INTO country VALUES ('Turkmenistan');
    INSERT INTO country VALUES ('Uganda');
    INSERT INTO country VALUES ('Ukraine');
    INSERT INTO country VALUES ('United Arab Emirates');
    INSERT INTO country VALUES ('United Kingdom');
    INSERT INTO country VALUES ('United States');
    INSERT INTO country VALUES ('Uruguay');
    INSERT INTO country VALUES ('New Zealand');
    INSERT INTO country VALUES ('Uzbekistan');
    INSERT INTO country VALUES ('Belarus');
    INSERT INTO country VALUES ('Venezuela');
    INSERT INTO country VALUES ('Russia');
    INSERT INTO country VALUES ('Vietnam');
    INSERT INTO country VALUES ('Yemen');
    INSERT INTO country VALUES ('Zimbabwe');








    

    -- osoitteet
    INSERT INTO address VALUES(1,'Esimerkkikatu 8 E','84958','Keuruu','Finland','Keski-Suomi',NULL);
    INSERT INTO address VALUES(2,'Ullakuja 13 U','19218','Savonlinna','Finland','Etelä-Savo',NULL);
    INSERT INTO address VALUES(3,'Ollilakuja 8 H','38495','Savonlinna','Finland','Etelä-Savo',NULL);
    INSERT INTO address VALUES(4,'Neilikkakatu 31 E','30495','Vantaa','Finland','Uusimaa',NULL);